<?php

namespace AppBundle\Repository;

/**
 * ArretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArretRepository extends \Doctrine\ORM\EntityRepository
{
}
