imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.images: /uploads/images/

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: 
        enabled: true
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/web/assets/manifest.json'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_rest:
    routing_loader:
        include_format: false
        default_format: html
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'html'], fallback_format: html, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
        
nelmio_cors:
    defaults:
        allow_origin:  ["*"]
        allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS", "PATCH"]
        allow_headers: ["*"]
        max_age:       86400
    paths:
        '^/': ~
lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Category:
            class: AppBundle\Entity\Category
            label: 'Metiers'
            list:
                actions:
                    - { name: 'new', label: 'Créer une codification' }
                title: 'Liste des metiers'
                sort: ['catFather', 'ASC']
                fields:
                    - Id
                    - { property: 'name', label: 'Nom' }
                    - { property: 'catFather', label: 'Clients' }
            form:
                fields:
                    - code
                    - { property: 'catFather', label: 'Parent' }
                    - { property: 'name', label: 'Nom' }
        Network:
            class: AppBundle\Entity\Network
            label: 'Reportage photos'
            list:
                actions:
                    - { name: 'new', label: 'Créer un nouveau reportage' }
                title: 'Liste des reportage'
                sort: ['name', 'ASC']
                fields:
                    - { property: 'name', label: 'Nom' }
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
        Line:
            class: AppBundle\Entity\Line
            label: 'Vidéos'
            list:
                actions:
                    - { name: 'new', label: 'Créer une vidéos' }
                title: 'Liste des vidéos'
                sort: ['name', 'ASC']
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'network', label: 'metier'}
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'network', label: 'Network'}
        Stop:
            class: AppBundle\Entity\Stop
            label: 'Arrêts'
            list:
                actions:
                    - { name: 'new', label: 'Créer un arrêt' }
                title: 'Liste des arrêts'
                sort: ['name', 'ASC']
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'line', label: 'Ligne'}
            form:
                fields:
                    - { property: 'name', label: 'Nom' }
                    - { property: 'line', label: 'Ligne'}
        User:
            class: AppBundle\Entity\User
            label: 'Utilisateurs'
            list:
                actions:
                    - { name: 'new', label: 'Créer un utilisateur' }
                title: Liste des utilisateurs
                fields: 
                    - { property: 'name', label: 'Nom' }
                    - email
                sort: 'name'
            new:
                title: Création d'un utilisateur
                fields:
                    - name
                    - email
                    - enabled
                    - { property: 'plainPassword', type: 'text', type_options: { required: true }, label: 'Mot de passe' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Médiateur': 'ROLE_USER', 'Keolis': 'ROLE_KEOLIS', 'SNCF': 'ROLE_SNCF', 'Administrateur': 'ROLE_ADMIN' }, label: 'Groupes' } }
            edit:
                title: Modification d'un utilisateur
                fields:
                    - name
                    - email
                    - enabled
                    - { property: 'plainPassword', type: 'text', type_options: { required: false }, label: 'Mot de passe' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Médiateur': 'ROLE_USER', 'Keolis': 'ROLE_KEOLIS', 'SNCF': 'ROLE_SNCF', 'Administrateur': 'ROLE_ADMIN' }, label: 'Groupes' } }
        Task:
            class: AppBundle\Entity\Task
            label: 'Tâches'             
            list:
                actions:
                    - { name: 'new', label: 'Créer une tâche' }
                title: Liste des tâches 
                fields: 
                    - { property: 'title', label: 'Titre' }
                    - { property: 'users', label: 'Médiateurs' }
                    - { property: 'start', label: 'Début' }
                    - { property: 'end', label: 'Fin' }
            new:
                title: Création d'une tâche
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'text', label: 'Texte' }
                    - { property: 'start', label: 'Début' }
                    - { property: 'end', label: 'Fin' }
                    - { property: 'users', label: 'Médiateurs' }
            edit:
                title: Modification d'une tâche
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'text', label: 'Texte' }
                    - { property: 'start', label: 'Début' }
                    - { property: 'end', label: 'Fin' }
                    - { property: 'users', label: 'Médiateurs' }
        Information:
            class: AppBundle\Entity\Information
            label: 'Informations'             
            list:
                actions:
                    - { name: 'new', label: 'Créer une information' }
                title: 'Liste des informations'   
                fields: 
                    - { property: 'title', label: 'Titre' }
                    - { property: 'level', label: 'Niveau' }
                    - { property: 'text', label: 'Texte' }
                    - { property: 'start', label: 'Début' }
                    - { property: 'end', label: 'Fin' }
            new:
                title: Création d'une information
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'level', type: 'choice', type_options: { multiple: false, expanded: true, choices: { 'Vert': 'success', 'Orange': 'warning', 'Rouge': 'alert' }, label: 'Niveau' } }
                    - { property: 'text', label: 'Texte' }
                    - { property: 'start', label: 'Début' }
                    - { property: 'end', label: 'Fin' }
            edit:
                title: Modification d'une information
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'level', type: 'choice', type_options: { multiple: false, expanded: true, choices: { 'Vert': 'success', 'Orange': 'warning', 'Rouge': 'alert' }, label: 'Niveau' } }
                    - { property: 'text', label: 'Texte' }
                    - { property: 'start', label: 'Début' }
                    - { property: 'end', label: 'Fin' }
        Event:
            disabled_actions: [ 'new']
            class: AppBundle\Entity\Event
            label: 'Listes des CV'
            list:
                actions: [ '-edit','edit', 'delete',]
                title: 'Liste des CV'
                fields:
                    - { property: 'user', label: 'Nom'}
                    - { property: 'avatarIndex', label: 'avatar'}
                    - { property: 'nicename', label: 'surnom'}
                    - { property: 'textEmail', label: 'Email'}
                    - { property: 'textDate', label: 'Date de naissance'}
                    - { property: 'textSlogan', label: 'Slogan'}
                    - { property: 'myClass', label: 'Ma classe'}
                    - { property: 'myFavoriteSubject', label: 'Sujet favori'}
                    - { property: 'myBestNotation' , label: 'Ma meilleure matière'}
                    - { property: 'myDiploma' , label: 'Mes diplômes'}
                    - { property: 'myReward' , label: 'Mes récompenses'}
                    - { property: 'myTrainer' , label: 'Mes stages'}
                    - { property: 'action' , label: 'Action'}
                    - { property: 'myMovie', label: 'Mon film préféré'}
                    - { property: 'myCitation' , label: 'Ma citation préférée'}
                    - { property: 'myInterest' , label: 'Mes centres intérets'}
                    - { property: 'myHobby' , label: 'Mes hobbys'}
                    - { property: 'textReve' , label: 'Mon métier de rève'}
                    - { property: 'creation' , label: 'Creation'}
                    - { property: 'altercation' , label: 'Altercation'}
    site_name: 'Onyxp'
    design:
        brand_color: '#cacaca'

vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images'
   